const BLOOK_LIST = [
    'Chick',
    'Chicken',
    'Cow',
    'Goat',
    'Horse',
    'Pig',
    'Sheep',
    'Duck',
    'Alpaca',
    'Dog',
    'Cat',
    'Rabbit',
    'Goldfish',
    'Hamster',
    'Turtle',
    'Kitten',
    'Puppy',
    'Bear',
    'Moose',
    'Fox',
    'Raccoon',
    'Squirrel',
    'Owl',
    'Hedgehog',
    'Deer',
    'Wolf',
    'Beaver',
    'Tiger',
    'Orangutan',
    'Cockatoo',
    'Parrot',
    'Anaconda',
    'Jaguar',
    'Macaw',
    'Toucan',
    'Panther',
    'Capuchin',
    'Gorilla',
    'Hippo',
    'Rhino',
    'Giraffe',
    'Snowy Owl',
    'Polar Bear',
    'Arctic Fox',
    'Baby Penguin',
    'Penguin',
    'Arctic Hare',
    'Seal',
    'Walrus',
    'Witch',
    'Wizard',
    'Elf',
    'Fairy',
    'Slime Monster',
    'Jester',
    'Dragon',
    'Queen',
    'Unicorn',
    'King',
    'Two of Spades',
    'Eat Me',
    'Drink Me',
    'Alice',
    'Queen of Hearts',
    'Dormouse',
    'White Rabbit',
    'Cheshire Cat',
    'Caterpillar',
    'Mad Hatter',
    'King of Hearts',
    'Toast',
    'Cereal',
    'Yogurt',
    'Breakfast Combo',
    'Orange Juice',
    'Milk',
    'Waffle',
    'Pancakes',
    'French Toast',
    'Pizza',
    'Earth',
    'Meteor',
    'Stars',
    'Alien',
    'Planet',
    'UFO',
    'Spaceship',
    'Astronaut',
    'Lil Bot',
    'Lovely Bot',
    'Angry Bot',
    'Happy Bot',
    'Watson',
    'Buddy Bot',
    'Brainy Bot',
    'Mega Bot',
    'Old Boot',
    'Jellyfish',
    'Clownfish',
    'Frog',
    'Crab',
    'Pufferfish',
    'Blobfish',
    'Octopus',
    'Narwhal',
    'Dolphin',
    'Baby Shark',
    'Megalodon',
    'Panda',
    'Sloth',
    'Tenrec',
    'Flamingo',
    'Zebra',
    'Elephant',
    'Lemur',
    'Peacock',
    'Chameleon',
    'Lion',
    'Amber',
    'Dino Egg',
    'Dino Fossil',
    'Stegosaurus',
    'Velociraptor',
    'Brontosaurus',
    'Triceratops',
    'Tyrannosaurus Rex',
    'Ice Bat',
    'Ice Bug',
    'Ice Elemental',
    'Rock Monster',
    'Dink',
    'Donk',
    'Bush Monster',
    'Yeti',
    'Dingo',
    'Echidna',
    'Koala',
    'Kookaburra',
    'Platypus',
    'Joey',
    'Kangaroo',
    'Crocodile',
    'Sugar Glider',
    'Deckhand',
    'Buccaneer',
    'Swashbuckler',
    'Treasure Map',
    'Seagull',
    'Jolly Pirate',
    'Pirate Ship',
    'Kraken',
    'Captain Blackbeard',
    'Ant',
    'Rhino Beetle',
    'Ladybug',
    'Fly',
    'Worm',
    'Bee',
    'Mantis',
    'Butterfly',
    'Bananas',
    'Watermelon',
    'Cheese',
    'Doughnut',
    'Taco',
    'Bao',
    'Sushi',
    'Cheeseburger',
    'Sandwich',
    'Pumpkin',
    'Swamp Monster',
    'Frankenstein',
    'Vampire',
    'Zombie',
    'Mummy',
    'Caramel Apple',
    'Candy Corn',
    'Crow',
    'Vampire Bat',
    'Werewolf',
    'Ghost',
    'Black Bear',
    'Pumpkin Pie',
    'Chipmunk',
    'Cornucopia',
    'Autumn Cat',
    'Pumpkin Puppy',
    'Autumn Crow',
    'Turkey',
    'Snow Globe',
    'Holiday Gift',
    'Hot Chocolate',
    'Holiday Wreath',
    'Stocking',
    'Gingerbread Man',
    'Gingerbread House',
    'Reindeer',
    'Snowman',
    'Santa Claus',
    'Rainbow Jellyfish',
    'Blizzard Clownfish',
    'Lovely Frog',
    'Lucky Frog',
    'Spring Frog',
    'Poison Dart Frog',
    'Lucky Hamster',
    'Lucky Bee',
    'Chocolate Rabbit',
    'Spring Rabbit',
    'Spring Deer',
    'Lemon Crab',
    'Pirate Pufferfish',
    'Donut Blobfish',
    'Crimson Octopus',
    'Rainbow Narwhal',
    'Frost Wreath',
    'Tropical Globe',
    'New York Snow Globe',
    'London Snow Globe',
    'Japan Snow Globe',
    'Egypt Snow Globe',
    'Paris Snow Globe',
    'Red Sweater Snowman',
    'Blue Sweater Snowman',
    'Elf Sweater Snowman',
    'Holiday Elf',
    'Cozy Baby Penguin',
    'Santa Claws',
    'Cookies Combo',
    'Chilly Flamingo',
    'Snowy Bush Monster',
    'Nutcracker Koala',
    'Half a Sandwich',
    'Ice Slime',
    'Frozen Fossil',
    'Ice Crab',
    'Rainbow Panda',
    'White Peacock',
    'Tiger Zebra',
    'Teal Platypus',
    'Golden Pumpkin Pie',
    'Blue Butterfly',
    'Red Astronaut',
    'Orange Astronaut',
    'Yellow Astronaut',
    'Lime Astronaut',
    'Green Astronaut',
    'Cyan Astronaut',
    'Blue Astronaut',
    'Pink Astronaut',
    'Purple Astronaut',
    'Brown Astronaut',
    'Black Astronaut',
    'Lovely Planet',
    'Lovely Peacock',
    'Lovely Fox',
    'Lovely Rabbit',
    'Haunted Pumpkin',
    'Pumpkin Cookie',
    'Ghost Cookie',
    'Red Gummy Bear',
    'Blue Gummy Bear',
    'Green Gummy Bear',
    'Skeleton Fish',
    'Super Glider',
    'Chick Chicken',
    'Chicken Chick',
    'Raccoon Bandit',
    'Owl Sheriff',
    'Vampire Frog',
    'Pumpkin King',
    'Leprechaun',
    'Anaconda Wizard',
    'Spooky Pumpkin',
    'Spooky Mummy',
    'Agent Owl',
    'Master Elf',
    'Party Pig',
    'Wise Owl',
    'Wise Caterpillar',
    'Spooky Ghost',
    'Phantom King',
    'Tim the Alien',
    'Rainbow Astronaut',
    'Hamsta Claus',
    'Light Blue',
    'Black',
    'Red',
    'Purple',
    'Pink',
    'Orange',
    'Lime',
    'Green',
    'Teal',
    'Tan',
    'Maroon',
    'Gray',
    'Mint',
    'Salmon',
    'Burgandy',
    'Baby Blue',
    'Dust',
    'Brown',
    'Dull Blue',
    'Yellow',
    'Blue'
];

export default BLOOK_LIST;
